name: CI/CD Pipeline

on: push

env:
  DEPLOY_STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

permissions:
  id-token: write
  contents: read

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo Test
        run: |
          echo "Hello World"
          echo "Deploy Stage: $DEPLOY_STAGE"
  lint:
    needs: [test_action]
    uses: ./.github/workflows/static-analysis.yml
    with:
      lint_dir: src/


