name: CI/CD Pipeline

on: push

env:
  DEPLOY_STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/static-analysis.yml
    with:
      lint_dir: ./
  
  # test:
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     package_dir: src/
  #     test_dir: tests/
  #     requirements_file: src/requirements.txt



